### ISSUE TITLE
Diagnostics integration does not work

### ISSUE THREAD

**Issue by aitvann** [ghostbuster91/nvim-next#16]
I tried all of this
```vim
:lua require("nvim-next.integrations").diagnostic().goto_next({ severity = { min = vim.diagnostic.severity.HINT } })
:lua require("nvim-next.integrations").diagnostic().goto_next({ severity = { min = vim.diagnostic.severity.ERROR } })
:lua require("nvim-next.integrations").diagnostic().goto_next()
```
and my cursor isn't going anywhere. even tho just `:lua vim.diagnostic.goto_next()` works as expected. [Treesitter text-objects](https://github.com/ghostbuster91/nvim-next#treesitter-text-objects) and [Gitsigns](https://github.com/ghostbuster91/nvim-next#gitsigns) integrations work no problem

**Comment by ghostbuster91** [comment]
Hi,

thanks for reporting. 
The problem is that this:
```lua
require("nvim-next.integrations").diagnostic().goto_next()
```
returns a function, so you need to call it one more time:
```lua
require("nvim-next.integrations").diagnostic().goto_next()()
```

I know, that is kind of not very intuitive but it was necessary so that we can pass some additional arguments like the `severity`. 

Here are my bindings:
https://github.com/ghostbuster91/dot-files/blob/master/programs/neovim/init.lua#L142-L145

Let me know if this works for you and if you think that the documentation should be improved somehow.

**Comment by aitvann** [comment]
now I see. thank you for the answer and for an awesome plugin !
